USE CONSTELLATION_TEST
GO

-- OFFERINGRESOURCES TABLE --
ALTER TABLE OFFERINGRESOURCES NOCHECK CONSTRAINT ALL;
SET IDENTITY_INSERT OFFERINGRESOURCES ON;

INSERT INTO OFFERINGRESOURCES (Id, Title, UrlPath, OfferingId, ShowLink)
SELECT Id, Title, UrlPath, OfferingId, ShowLink FROM [ACOS_TEST].[dbo].OFFERINGRESOURCES
WHERE 1 = 1;

SET IDENTITY_INSERT OFFERINGRESOURCES OFF;
ALTER TABLE OFFERINGRESOURCES WITH CHECK CHECK CONSTRAINT ALL;

-- COURSEOFFERINGLESSON TABLE --
ALTER TABLE COURSEOFFERINGLESSON NOCHECK CONSTRAINT ALL;

INSERT INTO COURSEOFFERINGLESSON (LessonsId, OfferingsId)
SELECT Lesson_Id, CourseOffering_Id FROM [ACOS_TEST].[dbo].LessonCourseOfferings
WHERE 1 = 1;

ALTER TABLE COURSEOFFERINGLESSON WITH CHECK CHECK CONSTRAINT ALL;

-- ABSENCES TABLE --
ALTER TABLE ABSENCES NOCHECK CONSTRAINT ALL;

INSERT INTO ABSENCES (Id, Type, StudentId, OfferingId, Date, PeriodName, PeriodTimeframe, AbsenceLength, AbsenceTimeframe, AbsenceReason, StartTime, EndTime, ExternallyExplained, ExternalExplanation, ExternalExplanationSource, DateScanned, LastSeen)
SELECT Id, Type, StudentId, OfferingId, Date AS datetime2, PeriodName, PeriodTimeframe, AbsenceLength, AbsenceTimeframe, AbsenceReason, StartTime, EndTime, ExternallyExplained, ExternalExplanation, ExternalExplanationSource, DateScanned AS datetime2, LastSeen AS datetiem2 FROM [ACOS_TEST].[dbo].[ABSENCES]
WHERE 1 = 1;

ALTER TABLE ABSENCES WITH CHECK CHECK CONSTRAINT ALL;

-- CLASSCOVERS TABLE --
ALTER TABLE COVERS NOCHECK CONSTRAINT ALL;
SET IDENTITY_INSERT COVERS ON;

INSERT INTO COVERS (Id, OfferingId, StartDate, EndDate, IsDeleted, UserType, CasualId, StaffId)
SELECT Id, OfferingId, StartDate AS datetime2, EndDate AS datetime2, IsDeleted, UserType, CasualId, StaffId FROM [ACOS_TEST].[dbo].[CLASSCOVERS]
WHERE 1 = 1;

SET IDENTITY_INSERT COVERS OFF;
ALTER TABLE COVERS WITH CHECK CHECK CONSTRAINT ALL;

-- ENROLMENTS TABLE --
ALTER TABLE ENROLMENTS NOCHECK CONSTRAINT ALL;
SET IDENTITY_INSERT ENROLMENTS ON;

INSERT INTO ENROLMENTS (Id, StudentId, OfferingId, IsDeleted, DateCreated, DateDeleted)
SELECT Id, StudentId, OfferingId, IsDeleted, DateCreated AS datetime2, DateDeleted AS datetime2 FROM [ACOS_TEST].[dbo].[ENROLMENTS]
WHERE 1 = 1;

SET IDENTITY_INSERT ENROLMENTS OFF;
ALTER TABLE ENROLMENTS WITH CHECK CHECK CONSTRAINT ALL;

-- OFFERINGSESSIONS TABLE --
ALTER TABLE SESSIONS NOCHECK CONSTRAINT ALL;
SET IDENTITY_INSERT SESSIONS ON;

INSERT INTO SESSIONS (Id, OfferingId, StaffId, PeriodId, RoomId, IsDeleted, DateCreated, DateDeleted)
SELECT Id, OfferingId, StaffId, PeriodId, RoomId, IsDeleted, DateCreated AS datetime2, DateDeleted AS datetime2 FROM [ACOS_TEST].[dbo].OfferingSessions
WHERE 1 = 1;

SET IDENTITY_INSERT SESSIONS OFF;
ALTER TABLE SESSIONS WITH CHECK CHECK CONSTRAINT ALL;

GO