USE CONSTELLATION_TEST
GO

-- COURSES TABLE --
ALTER TABLE COURSES NOCHECK CONSTRAINT ALL;
SET IDENTITY_INSERT COURSES ON;

INSERT INTO COURSES (Id, Name, Grade, Faculty, HeadTeacherId, FullTimeEquivalentValue)
SELECT Id, Name, Grade, Faculty, HeadTeacher_StaffId, FullTimeEquivalentValue FROM [ACOS_TEST].[dbo].[COURSES]
WHERE 1 = 1;

SET IDENTITY_INSERT COURSES OFF;
ALTER TABLE COURSES WITH CHECK CHECK CONSTRAINT ALL;

-- DEVICEALLOCATIONS TABLE --
ALTER TABLE DEVICEALLOCATIONS NOCHECK CONSTRAINT ALL;
SET IDENTITY_INSERT DEVICEALLOCATIONS ON;

INSERT INTO DEVICEALLOCATIONS (Id, StudentId, SerialNumber, DateAllocated, IsDeleted, DateDeleted)
SELECT Id, StudentId, SerialNumber, DateAllocated AS datetime2, IsDeleted, DateDeleted AS datetime2 FROM [ACOS_TEST].[dbo].[DEVICEALLOCATIONS]
WHERE 1 = 1;

SET IDENTITY_INSERT DEVICEALLOCATIONS OFF;
ALTER TABLE DEVICEALLOCATIONS WITH CHECK CHECK CONSTRAINT ALL;

-- LESSONROLLSTUDENTATTENDANCES TABLE --
ALTER TABLE LESSONROLLSTUDENTATTENDANCE NOCHECK CONSTRAINT ALL;

INSERT INTO LESSONROLLSTUDENTATTENDANCE (Id, LessonRollId, StudentId, Present)
SELECT Id, LessonRollId, StudentId, Present FROM [ACOS_TEST].[dbo].[LessonRollStudentAttendances]
WHERE 1 = 1;

ALTER TABLE LESSONROLLSTUDENTATTENDANCE WITH CHECK CHECK CONSTRAINT ALL;

GO