<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

	<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constellation.Application\Constellation.Application.csproj" />
    <ProjectReference Include="..\Constellation.Presentation.Shared\Constellation.Presentation.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Staff\Pages\Partner\Enrolments\Reports\" />
    <Folder Include="Areas\Staff\Pages\Partner\Enrolments\Offers\" />
  </ItemGroup>


</Project>
