<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="ExternalResources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constellation.Application\Constellation.Application.csproj" />
    <ProjectReference Include="..\Constellation.Core\Constellation.Core.csproj" />
    <ProjectReference Include="..\Constellation.Infrastructure.Templates\Constellation.Infrastructure.Templates.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="EPPlus" />
    <PackageReference Include="ExcelDataReader" />
    <PackageReference Include="ExcelDataReader.DataSet" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Microsoft.PowerShell.SDK" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Select.HtmlToPdf.NetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="System.DirectoryServices" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" />
    <PackageReference Include="System.Management.Automation" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\EnrolmentContext\Migrations\" />
  </ItemGroup>

</Project>
