<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Domains\EmergencyConsole\Helpers\**" />
    <EmbeddedResource Remove="Domains\EmergencyConsole\Helpers\**" />
    <None Remove="Domains\EmergencyConsole\Helpers\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constellation.Core\Constellation.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="EPPlus" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
	    <PackageReference Include="HtmlAgilityPack" />
	    <PackageReference Include="MediatR" />
	    <PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" />
		<PackageReference Include="Microsoft.Extensions.Identity.Stores" />
		<PackageReference Include="Serilog.Extensions.Logging" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Constellation.Application.Tests.Unit</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Domains\Edval\Events\EdvalTimetablesUpdated\" />
	  <Folder Include="Domains\Edval\Models\" />
	  <Folder Include="Domains\Faculties\Events\FacultyMemberAddedDomainEvent\" />
	  <Folder Include="Domains\Faculties\Events\FacultyMemberRemovedDomainEvent\" />
	  <Folder Include="Domains\Messaging\Email\Queries\" />
	  <Folder Include="Domains\Messaging\Sms\Queries\" />
	  <Folder Include="Domains\Operations\" />
	  <Folder Include="Domains\WorkFlows\Enums\" />
	</ItemGroup>

</Project>