<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<VersionPrefix>1.19.3</VersionPrefix>
	</PropertyGroup>

	<PropertyGroup>
		<AnalysisLevel>latest</AnalysisLevel>
	    <AnalysisMode>All</AnalysisMode>
	</PropertyGroup>
	
	<ItemGroup Condition="'$(MSBuildProjectName)' != 'Constellation.Analyzers'">
		<ProjectReference Include="$(MSBuildThisFileDirectory)..\build\Constellation.Analyzers\Constellation.Analyzers.csproj"
		                  OutputItemType="Analyzer"
		                  ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
