<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyVersion>1.18.4.26027</AssemblyVersion>
	</PropertyGroup>

	<PropertyGroup>
		<AnalysisLevel>latest</AnalysisLevel>
	    <AnalysisMode>All</AnalysisMode>
	</PropertyGroup>
</Project>