<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\EnrolmentContext\Application\Enums\**" />
    <EmbeddedResource Remove="Models\EnrolmentContext\Application\Enums\**" />
    <None Remove="Models\EnrolmentContext\Application\Enums\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\LinkedSystems\Errors\" />
    <Folder Include="Models\ThirdPartyConsent\Events\" />
    <Folder Include="Models\Timetables\Events\" />
    <Folder Include="Models\Training\Events\" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Development\repos\Constellation\src\Constellation.Core\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Development\repos\Constellation\src\Constellation.Core\.editorconfig" />
  </ItemGroup>

</Project>
